{
 "title": "TARPN Battery Board Deluxe v2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Supply Switch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{board_state=\"Standby\"}"
    }
   ]
  },
  {
   "title": "Battery Switch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{board_state=\"Backup\"}"
    }
   ]
  },
  {
   "title": "RPi",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpi_on" }
   ]
  },
  {
   "title": "Supply Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "supply_volts" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "battery_volts" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "supply_volts" },
    { "expr": "battery_volts" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "load_amps" },
    { "expr": "avg_over_time(load_amps[5m])" }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(supply_volts > 5 or battery_volts) * load_amps"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature_celcius * 1.8 + 32", "legendFormat": "F" },
    { "expr": "temperature_celcius" }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "load_ah", "legendFormat": "Charge Consumed" },
    {
     "expr": "(supply_volts > 5 or battery_volts) * load_ah",
     "legendFormat": "Power Consumed"
    }
   ]
  },
  {
   "title": "Board State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    { "expr": "board_state", "legendFormat": "{{board_state}}" }
   ]
  },
  {
   "title": "Serial Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    { "expr": "serial_lines_total", "legendFormat": "Serial Lines Received" },
    { "expr": "serial_errors_total", "legendFormat": "Serial Decoding Errors" }
   ]
  }
 ]
}